### ISSUE TITLE
Error starting on WildFly 8.2.0

### ISSUE THREAD

**Issue by vibe13** [project-ncl/pnc#168]
When deploying master on WildFly I get the following error: 
"Managed bean class org.jclouds.functions.OnlyElementOrNull must be @Dependent".
Running on EAP gives me no problems.

**Comment by jbartece** [comment]
Are you sure, that you are using Wildfly 8.2.0 or above? There is an issues with Weld in Wildfly 8.1.0, which tries to load no CDI libraries as CDI beans.

**Comment by vibe13** [comment]
@jbartece after a cleanup, I can confirm that with Wildfly 8.2.0 deployments is fine, no problems. Closing.
